
nyx_rsm:
  # Where data_loader should gets it data
  data: data/nyx_8_7_data/
  groups: resources/native_all_filtered.txt

  # If left true, data_loader will load or dump to a pkl
  # RSM will compute its scores and allow other tasks to access it
  # so it's nice to compute this once, leave force_process to false
  # and mess around with viz
  force_process: false

  # configurations
  procs:
    - 1
    - 4
    - 8
    - 16
    - 32
  
  # Pre-processing done on data
  data_remove: false
  data_rescale: true
  data_norm: false

  # modules to run
  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    #- modules.example_rsm.test   # This module comes after the compute
    #- viz.barchart.create_barchart
    #- modules.eff.print_loss
    #- viz.heatmap.create_heatmap
    - viz.bubble.bubble
    #- viz.sunburst.sunburst
    #- viz.linechart.effloss_vs_counter_val
  
  # rsm settings
  rsm_iters: 100
  rsm_print: true
  rsm_use_nn_solver: false

  # If set, rsm data will be written out
  # Comment out if not desired
  csv_rsm_results: 'output/nyx/nyx_rsm.csv'
  csv_rsm_res_errors: 'output/nyx/nyx_rsm_res_err.csv'
  csv_rsm_ev_errors: 'output/nyx/nyx_rsm_ev_err.csv'
  csv_rsm_alphas: 'output/nyx/nyx_rsm_weights.csv'
  
  # viz settings
  # NOTE: Most of these variables are depricated
  # These viz modules should use the paths specified above by rsm
  # eventually for clarity and readability
  show_plot: false
  save_plot: false
  csv_path: 'output/nyx/nyx_rsm.csv'
  rsm_path: 'output/nyx/nyx_rsm.csv'
  rsm_alpha_path: 'output/nyx/nyx_rsm_weights.csv'
  rsm_err_path: 'output/nyx/nyx_rsm_res_err.csv'
  plt_title: 'nyx'

  # heatmap
  heat_output: 'viz/output/nyx/nyx_rsm.png'

  # bar
  bar_output: 'viz/output/nyx/nyx_bar_%s.png'

  # effeciency
  eff_output: 'viz/output/nyx/nyx_eff_%s.png'

  # bubble
  bubble_n: 10
  bubble_output: 'viz/output/nyx/nyx_bubble_%s.pdf'
  # line
  line_output: 'viz/output/nyx/nyx_line_%s.png'


# Exact same as above, except uses nn solver
nyx_rsm_nn:
  data: data/nyx_8_7_data/
  groups: resources/native_all_filtered.txt
  force_process: false

  procs:
    - 1
    - 4
    - 8
    - 16
    - 32
  
  data_remove: false
  data_rescale: true
  data_norm: false

  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    - viz.barchart.create_barchart
    - modules.eff.print_loss
    - viz.heatmap.create_heatmap
  
  # rsm settings
  rsm_iters: 10000
  rsm_print: true
  rsm_use_nn_solver: true

  csv_rsm_results: 'output/nyx_nn/nyx_rsm.csv'
  csv_rsm_res_errors: 'output/nyx_nn/nyx_rsm_res_err.csv'
  csv_rsm_ev_errors: 'output/nyx_nn/nyx_rsm_ev_err.csv'
  csv_rsm_alphas: 'output/nyx_nn/nyx_rsm_weights.csv'
  
  show_plot: false
  save_plot: true
  csv_path: 'output/nyx_nn/nyx_rsm.csv'
  rsm_path: 'output/nyx_nn/nyx_rsm.csv'
  rsm_alpha_path: 'output/nyx_nn/nyx_rsm_weights.csv'
  rsm_err_path: 'output/nyx_nn/nyx_rsm_res_err.csv'
  plt_title: 'nyx'

  heat_output: 'viz/output/nyx_nn/nyx_rsm.png'
  bar_output: 'viz/output/nyx_nn/nyx_bar_%s.png'
  eff_output: 'viz/output/nyx_nn/nyx_eff_%s.png'
  bubble_n: 10
  bubble_output: 'viz/output/nyx_nn/nyx_bubble_%s.pdf'
  line_output: 'viz/output/nyx_nn/nyx_line_%s.png'

