
warpx_rsm_new:
  # Where data_loader should gets it data
  data: data/warpx/
  groups: resources/native_all_filtered.txt

  # If left true, data_loader will load or dump to a pkl
  # RSM will compute its scores and allow other tasks to access it
  # so it's nice to compute this once, leave force_process to false
  # and mess around with viz
  force_process: true

  # configurations
  procs:
    - 1
    - 2
    - 4
    - 8
    - 12
    - 16
    - 20
    - 24
    - 28
    - 32
  
  # Pre-processing done on data
  data_remove: false
  data_rescale: true
  data_norm: false

  # modules to run
  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    #- modules.example_rsm.test   # This module comes after the compute
    #- viz.barchart.create_barchart
    #- modules.eff.print_loss
    - viz.heatmap.create_heatmap
    #- viz.bubble.bubble
    - viz.sunburst.sunburst
    #- viz.linechart.effloss_vs_counter_val
  
  # rsm settings
  rsm_iters: 100
  rsm_print: true
  rsm_use_nn_solver: true

  # If set, rsm data will be written out
  # Comment out if not desired
  csv_rsm_results: 'output/warpx_new/warpx_rsm.csv'
  csv_rsm_res_errors: 'output/warpx_new/warpx_rsm_res_err.csv'
  csv_rsm_ev_errors: 'output/warpx_new/warpx_rsm_ev_err.csv'
  csv_rsm_alphas: 'output/warpx_new/warpx_rsm_weights.csv'
  
  # viz settings
  # NOTE: Most of these variables are depricated
  # These viz modules should use the paths specified above by rsm
  # eventually for clarity and readability
  show_plot: false
  save_plot: true
  csv_path: 'output/warpx_new/warpx_rsm.csv'
  rsm_path: 'output/warpx_new/warpx_rsm.csv'
  rsm_alpha_path: 'output/warpx_new/warpx_rsm_weights.csv'
  rsm_err_path: 'output/warpx_new/warpx_rsm_res_err.csv'
  plt_title: 'warpx'

  # heatmap
  heat_output: 'viz/output/warpx_new/warpx_rsm.png'

  # bar
  bar_output: 'viz/output/warpx_new/warpx_bar_%s.png'

  # effeciency
  eff_output: 'viz/output/warpx_new/warpx_eff_%s.png'

  # bubble
  bubble_n: 10
  bubble_output: 'viz/output/warpx_new/warpx_bubble_%s.pdf'
  # line
  line_output: 'viz/output/warpx_new/warpx_line_%s.png'



